/* PRIMEIRA FORMA NORMAL */

/* 1- TODO CAMPO VETORIZADO SE TORNARA OUTRA TABELA 
	
		[VERMELHO, VERDE, AZUL] = VETOR DE CORES(DO MESMO TIPO)
	
   2- TODO CAMPO MULTIVALORADO SE TORNARA OUTRA TABELA
   
		[BAIRRO, CIDADE, ESTADO] = ENDERECO(NAO SAO DO MESMO TIPO)
   
   3- TODA A TABELA NECESSITA DE PELO MENOS UM CAMPO QUE
   IDENTIFIQUE TODO REGISTRO COMO SENDO UNICO 
   
		CHAVE PRIMARIA */
		
/* REGRAS DE CARDINALIDADE SERAO DEFINIDAS PELO ANALISTA DE NEGOCIOS */