/* DATAS */

USE EMPRESA
GO

SELECT * FROM ALUNO
GO

/* DATEDIFF - CALCULA DIFERENÇA ENTRE DUAS DATAS 
   GETDATE() - TRAZ DIA E HORA
*/

SELECT NOME, GETDATE() AS "DATA" FROM ALUNO
GO

SELECT NOME, DATEDIFF(year, NASCIMENTO, GETDATE()) AS "IDADE" 
FROM ALUNO
GO

/* OPERAÇÃO MATEMÁTICA */

SELECT NOME, (DATEDIFF(MONTH, NASCIMENTO, GETDATE())/12) AS "IDADE" 
FROM ALUNO
GO

/* DATENAME - TRAZ O NOME DA PARTE DA DATA */

SELECT NOME, DATENAME(MONTH, NASCIMENTO) AS "DATA" 
FROM ALUNO
GO

SELECT NOME, DATENAME(WEEKDAY, NASCIMENTO) AS "DATA" 
FROM ALUNO
GO

/* DATEPART - RETORNA INTEIRO */

SELECT NOME, DATEPART(MONTH, NASCIMENTO) AS "DATA" 
FROM ALUNO
GO

/* DATEADD - RETORNA UMA DATA SOMANDO A OUTRA */

SELECT NOME, DATEADD(MONTH, 365, GETDATE()) AS "DATA" 
FROM ALUNO
GO

/* CONVERSÃO DE DADOS */

SELECT 'BANCO DE DADOS' + 1
GO

SELECT CAST('1' AS INT) + CAST ('1' AS INT) AS RESPOSTA
GO

/* APLICANDO */

USE EMPRESA

SELECT NOME, NASCIMENTO
FROM ALUNO

SELECT NOME,
DAY(NASCIMENTO) + '/' + MONTH(NASCIMENTO) + '/' + YEAR(NASCIMENTO)
FROM ALUNO
GO

SELECT NOME,
CAST(DAY(NASCIMENTO) AS VARCHAR) + '/' + 
CAST(MONTH(NASCIMENTO) AS VARCHAR) + '/' + 
CAST(YEAR(NASCIMENTO) AS VARCHAR) AS "NASCIMENTO"
FROM ALUNO
GO