-- SUBQUERIES

-- VENDEDOR QUE VENDEU MENOS EM MARCO E O SEU NOME

SELECT NOME, MARCO
FROM VENDEDOR
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDOR);

-- VENDEDOR QUE VENDEU MAIS EM MARCO E O SEU NOME

SELECT NOME, MARCO
FROM VENDEDOR
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDOR);

-- VENDEDOR QUE VENDEU MAIS QUE A MEDIA EM MARCO E O SEU NOME

SELECT NOME, MARCO FROM VENDEDOR
WHERE MARCO > (SELECT AVG(MARCO) FROM VENDEDOR);

-- OPERACOES EM LINHA

SELECT NOME, JANEIRO, FEVEREIRO, MARCO, 
(JANEIRO+FEVEREIRO+MARCO) AS "TOTAL",
TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3,2) AS "MEDIA FROM VENDEDORES"
FROM VENDEDOR;

-- APLICANDO DESCONTO

SELECT NOME, JANEIRO, FEVEREIRO, MARCO, 
(JANEIRO+FEVEREIRO+MARCO) AS "TOTAL",
(JANEIRO+FEVEREIRO+MARCO)*.10 AS "COMISSAO 10%",
TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3,2) AS "MEDIA FROM VENDEDORES"
FROM VENDEDOR;