/* SELECT */

/* FUNCAO PARA VER O HORARIO E DATA NO BANCO DE DADOS */
SELECT NOW();

/* SELECT PARA DIGITAR QUALQUER DADO */
SELECT 'Banco de Dados'

/* ALIAS(APELIDOS) DE COLUNAS */
SELECT 'Paula Fernandes' AS PROFESSORA;

/* SELECIONANDO APENAS ALGUNS ATRIBUTOS DA TABELA */
SELECT NOME,CPF,SEXO FROM CLIENTE;

/* FILTRO USANDO WHERE */
SELECT NOME,CPF,ENDERECO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME,CPF,ENDERECO FROM CLIENTE
WHERE NOME = 'Valdomiro Santiago';

/* USANDO O LIKE */
SELECT NOME,CPF,ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%SP';
/* CARACTER CORINGA % SIGNIFICA TUDO ANTES E TUDO DEPOIS*/
SELECT NOME,CPF,ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE 'IJUI%';