/* CONECTANDO A UM BANCO */

USE EMPRESA
GO

/* CRIAÇÃO DE TABELAS */

CREATE TABLE ALUNO(
	IDALU INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(30) NOT NULL UNIQUE
)
GO

/* CONSTRAINTS */

ALTER TABLE ALUNO 
ADD CONSTRAINT CK_SEXO CHECK (SEXO IN('M','F'))
GO

/* 1 X 1 */

CREATE TABLE ENDERECO (
	IDEND INT PRIMARY KEY IDENTITY(100,10),
	BAIRRO VARCHAR(30) NOT NULL,
	UF CHAR(2) NOT NULL
	CHECK (UF IN('RJ','SP','RS')),
	ID_ALU INT UNIQUE
)
GO

/* FOREIGN KEY */

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ENDERECO_ALUNO
FOREIGN KEY(ID_ALU) REFERENCES ALUNO(IDALU)
GO

/* DESCRIÇÃO */

SP_COLUMNS ALUNO
GO

SP_HELP ALUNO
GO

/* INSERÇÕES */

INSERT INTO ALUNO VALUES('VALDOMIRO','M','1999/07/27','VALDOMIRO@SQL.COM')
INSERT INTO ALUNO VALUES('GISLAINE','F','1988/09/12','GISLAINE@SQL.COM')
INSERT INTO ALUNO VALUES('LITURGO','M','1977/03/31','LITURGO@SQL.COM')
INSERT INTO ALUNO VALUES('VANESSA','F','1994/05/13','VANESSA@SQL.COM')
GO

SELECT * FROM ALUNO
GO

INSERT INTO ENDERECO VALUES('Morada do Vale I','RS',1)
INSERT INTO ENDERECO VALUES('Betania','SP',2)
INSERT INTO ENDERECO VALUES('Ibirapuera','RJ',3)
INSERT INTO ENDERECO VALUES('Morada do Vale II','RS',4)
GO

SELECT * FROM ENDERECO
GO

/* TELEFONE */

CREATE TABLE TELEFONE(
	IDTEL INT PRIMARY KEY IDENTITY,
	NUMERO VARCHAR(10) NOT NULL,
	TIPO CHAR(3) NOT NULL,
	ID_ALUNO INT,
	CHECK (TIPO IN('RES','COM','CEL'))
)
GO

INSERT INTO TELEFONE VALUES('93939190','RES',1)
INSERT INTO TELEFONE VALUES('98885931','COM',2)
INSERT INTO TELEFONE VALUES('91254123','COM',3)
INSERT INTO TELEFONE VALUES('95423157','CEL',4)
GO

SELECT * FROM ALUNO
GO

/* PEGAR DATA */

SELECT GETDATE()
GO

/* CLAUSULA AMBIGUA */

SELECT A.NOME,T.TIPO,T.NUMERO,E.BAIRRO,E.UF
FROM ALUNO A INNER JOIN TELEFONE T
ON A.IDALU = T.ID_ALUNO
INNER JOIN ENDERECO E
ON A.IDALU = E.ID_ALU
GO

-- IF NULL = ISNULL()

