/* Modelagem basica */

CLIENTE

NOME CARACTER(40)
CPF NUMERICO (11)
EMAIL CARACTER (30)
TELEFONE CARACTER (30)
SEXO CARACTER(1)
CIDADE CARACTER(50)

/* Processos de Modelagem */

/* ADM de Dados */

MODELAGEM CONCEITUAL - RASCUNHO 01

MODELAGEM LOGICA - BRMODELO

/* ADM OU DBA */

MODELAGEM FISICA - SCRIPT DB

/* MODELO FISICO */

/* CRIANDO UM BANCO */

CREATE DATABASE PROJETOUM;

/* CONECTANDO */

USE PROJETOUM;

/* CRIANDO A TABELA */

CREATE TABLE CLIENTE (
NOME VARCHAR(40) NOT NULL,
SEXO CHAR(1) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
CPF INT(11) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
ENDERECO VARCHAR(30) NOT NULL
);

/* VERIFICANDO AS TABELAS */

SHOW TABLES;

/* DESCREVENDO AS TABELAS */

DESC CLIENTE;

/* TIPOS DE VARIAVEIS */

CHAR E VARCHAR = JOAO, MATEMATICA, PALAVRA

FLOAT E INT = 3.14, 9, 7908

TEXT = TEXTO GRANDE

BLOB = ARQUIVOS E IMAGENS

1CHAR = 1BYTE
CHAR FICA DEFINITIVO, GASTA MAIS
VARCHAR PODE VARIAR E ECONOMIZAR ESPACO

ENUM = CONJUNTO DELIMITADO DE VALORES