/*
PRIMEIRA FORMA NORMAL: 

NENHUM CAMPO PODE SER DIVISIVEL (ENDERECO, RUA, BAIRRO)
NENHUM CAMPO PODE SER VETORIZADO (TELEFONE, 2 TELEFONES ETC)
PRECISA TER CHAVE PRIMARIA
*/

/*
SEGUNDA FORMA NORMAL:

CAMPO NAO CHAVE PRECISA DEPENDER DA TOTALIDADE DA CHAVE
EX: SE TEM O MEDICO,PACIENTE E HOSPITAL, TEM DATA, SE NAO, NAO TEM DATA
*/

/*
TERCEIRA FORMA NORMAL:

DEPENDENCIA TRANSITIVA, CAMPOS QUE DEPENDEM DE OUTROS CAMPOS NAO CHAVE
EX: SE O PACIENTE VAI NO HOSPITAL, NAO PRECISA SER INTERNADO, MAS DEPENDE DO DIAGNOSTICO. 
*/

-- CÓDIGO SOURCE BANCO DE DADOS

CREATE DATABASE CONSULTORIO;

USE CONSULTORIO;

CREATE TABLE PACIENTE(
		IDPAC INT PRIMARY KEY AUTO_INCREMENT,
		NOME VARCHAR(50),
		SEXO ENUM("M","F"),
		EMAIL VARCHAR(30),
		NASCIMENTO DATE
);

CREATE TABLE MEDICO(
		IDMED INT PRIMARY KEY AUTO_INCREMENT,
		NOME VARCHAR(50),
		SEXO ENUM("M","F"),
		ESPECIALIDADE VARCHAR(30),
		FUNCIONARIO ENUM("S","N")
);

CREATE TABLE HOSPITAL(
		IDHOS INT PRIMARY KEY AUTO_INCREMENT,
		NOME VARCHAR(50),
		BAIRRO VARCHAR(30),
		CIDADE VARCHAR(20),
		ESTADO CHAR(2)
);

CREATE TABLE CONSULTA(
		IDCON INT PRIMARY KEY AUTO_INCREMENT,
		ID_PAC INT,
		ID_MED INT,
		ID_HOS INT,
		DATA DATETIME,
		DIAGNOSTICO VARCHAR(50)
);

CREATE TABLE INTERNACAO(
		IDINT INT PRIMARY KEY AUTO_INCREMENT,
		ENTRADA DATETIME,
		QUARTO INT,
		SAIDA DATETIME,
		OBSERVACOES VARCHAR(70),
		ID_CON INT UNIQUE
);

-- CONSTRAINTS

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_PACIENTE
FOREIGN KEY(ID_PAC) REFERENCES PACIENTE(IDPAC);

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_MEDICO
FOREIGN KEY(ID_MED) REFERENCES MEDICO(IDMED);

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_HOSPITAL
FOREIGN KEY(ID_HOS) REFERENCES HOSPITAL(IDHOS);

ALTER TABLE INTERNACAO ADD CONSTRAINT FK_INTERNACAO_CONSULTA
FOREIGN KEY(ID_CON) REFERENCES CONSULTA(IDCON);

-- VERIFICANDO NO DICIONARIO DE DADOS

USE INFORMATION_SCHEMA;

DESC TABLES;

SELECT * FROM TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = "CONSULTORIO";