/* ORDER BY */

SELECT NOME,SEXO,CPF,CIDADE,BAIRRO,ESTADO
FROM CLIENTE
INNER JOIN ENDERECO
ON IDCLI = ID_CLI
ORDER BY NOME,CPF ASC; /* ELE PRIORIZA O PRIMEIRO ARGUMENTO, NO CASO NOME, ASC = ASCENDENTE */

ORDER BY 4 /* NUMERO DA COLUNA */

/* DELIMITADOR E ESTADO DO SERVIDOR */

SELECT * FROM CLIENTE; <--

DELIMITER $ --  TROCA O DELIMITADOR PARA $

-- STATUS DO SERVIDOR

STATUS