-- PROCEDURES COM PARAMETROS

CREATE TABLE CURSO(
IDCUR INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL,
CH INT(4) NOT NULL,
VALOR FLOAT(10,2) NOT NULL
);

INSERT INTO CURSO(NOME,CH,VALOR) VALUES('Informatica',1100,385.99);
INSERT INTO CURSO(NOME,CH,VALOR) VALUES('Administracao',990,271.99);
INSERT INTO CURSO(NOME,CH,VALOR) VALUES('Logistica',600,99.99);
INSERT INTO CURSO(NOME,CH,VALOR) VALUES('Financeiro',800,211.99);
INSERT INTO CURSO(NOME,CH,VALOR) VALUES('Recursos Humanos',1200,599.99);


DELIMITER $

-- PROCEDURE PARA CADASTRAR CLIENTE

CREATE PROCEDURE CADASTRAR_CURSO(PNOME VARCHAR(30), PCH INT(4), PVALOR FLOAT(10,2))
BEGIN
		INSERT INTO CURSO VALUES(NULL, PNOME,PCH,PVALOR);
END $

DELIMITER ;

CALL CADASTRAR_CURSO('Autodesk Autocad 2014',100,385.00);
-- ---------------------------------------------------------------------------------------

-- PROCEDURE PARA PROCURAR CLIENTE

DELIMITER $

CREATE PROCEDURE BUSCAR_CURSO()
BEGIN
		SELECT IDCUR, NOME, CH, VALOR
		FROM CURSO;
END 
$

DELIMITER ;

CALL BUSCAR_CURSO();