/* Queries - SELECAO - PROJECAO - JUNCAO */

/* PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM
RELATORIO COM O NOME, EMAIL E TELEFONE CELULAR 
DOS CLIENTES QUE MORAM NO ESTADO DO RIO GRANDE DO SUL
VOCE TERA QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */

SELECT C.NOME,C.EMAIL,T.NUMERO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLI = T.ID_CLI
INNER JOIN ENDERECO E
ON C.IDCLI = E.ID_CLI
WHERE T.TIPO = 'CEL' AND E.ESTADO = 'RS';

/* RESULTADO DA QUERY */
+--------+----------------+---------------+
| NOME   | EMAIL          | NUMERO        |
+--------+----------------+---------------+
| Althea | Althea@sql.com | 71 98598-3213 |
+--------+----------------+---------------+

/* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM 
RELATORIO COM O NOME, EMAIL E TELEFONE CELULAR
DAS MULHERES QUE MORAM NO ESTADO DE SAO PAULO
VOCE TERA QUE APSSAR A QUERY PARA GERAR O RELATORIO PARA O PROGRAMADOR */

SELECT C.NOME, C.EMAIL, T.NUMERO, E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON IDCLI = ID_CLI
INNER JOIN ENDERECO E
ON C.IDCLI = E.ID_CLI
WHERE C.SEXO = 'F' AND ESTADO = 'SP' AND T.TIPO = 'CEL';

/* RESULTADO DA QUERY */
+---------+-----------------+---------------+--------+
| NOME    | EMAIL           | NUMERO        | ESTADO |
+---------+-----------------+---------------+--------+
| Cecilia | Cecilia@sql.com | 88 99507-1234 | SP     |
+---------+-----------------+---------------+--------+

/* APLICANDO IFNULL */

SELECT C.NOME,IFNULL(C.EMAIL,'SEM EMAIL') AS "EMAIL",T.NUMERO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLI = T.ID_CLI
INNER JOIN ENDERECO E
ON C.IDCLI = E.ID_CLI
WHERE T.TIPO = 'CEL' AND E.ESTADO = 'SP';

/* RESULTADO DA QUERY */
+---------+-----------+---------------+
| NOME    | EMAIL     | NUMERO        |
+---------+-----------+---------------+
| Cecilia | SEM EMAIL | 88 99507-1234 |
+---------+-----------+---------------+

/* --------------------VIEWS-------------------- */

SELECT C.NOME,C.SEXO,IFNULL(C.EMAIL,"SEM EMAIL") AS "EMAIL",
T.TIPO,T.NUMERO,
E.BAIRRO,E.CIDADE,E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLI = T.ID_CLI
INNER JOIN ENDERECO E
ON C.IDCLI = E.ID_CLI;

/* CRIANDO A VIEW */

CREATE VIEW RELATORIO AS
SELECT C.NOME,C.SEXO,IFNULL(C.EMAIL,"SEM EMAIL") AS "EMAIL",
T.TIPO,T.NUMERO,
E.BAIRRO,E.CIDADE,E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLI = T.ID_CLI
INNER JOIN ENDERECO E
ON C.IDCLI = E.ID_CLI;

SELECT * FROM RELATORIO;

/* SELECAO DA VIEW(QUERY) */
SELECT * FROM RELATORIO
WHERE SEXO = 'F';

/* APAGANDO VIEW */
DROP VIEW RELATORIO;

/* FORMA DE ORGANIZAR VIEWS E TABLES */

CREATE VIEW V_RELATORIO AS
SELECT C.NOME,C.SEXO,IFNULL(C.EMAIL,"SEM EMAIL") AS "EMAIL",
T.TIPO,T.NUMERO,
E.BAIRRO,E.CIDADE,E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLI = T.ID_CLI
INNER JOIN ENDERECO E
ON C.IDCLI = E.ID_CLI;