/* TSQL = BLOCO DE LINGUAGEM DE PROGRAMAÇÃO 
PROGRAMAS SÃO UNIDADES QUE PODEM SER CHAMADOS
DE BLOCOS ANONIMOS.
BLOCOS ANONIMOS NÃO RECEBEM NOME, POIS NÃO
SAO SALVOS NO BANCO (PODEMOS CRIAR BLOCOS ANONIMOS
QUANDO QUEREMOS EXECUTAR UM COMANDO UMA UNICA VEZ
*/

/* BLOCO DE EXECUÇÃO */

BEGIN
	PRINT 'HELLO WORLD'
END
GO

/* BLOCO DE ATRIBUIÇÃO DE VARIAVEIS */

DECLARE
	@CONTADOR INT
BEGIN
	SET @CONTADOR = 5
	PRINT @CONTADOR
END
GO

/* NO SQL SERVER, CADA COLUNA, VARIAVEL, LOCAL, EXPRESSÃO E PARAMETRO TEM UM TIPO */

DECLARE
	@V_NUMERO NUMERIC(10,2) = 100.52,
	@V_DATA DATETIME = '20180212'
BEGIN
	PRINT 'VALOR NUMERICO: ' + CAST(@V_NUMERO AS VARCHAR)
	PRINT 'VALOR NUMERICO: ' + CONVERT(VARCHAR, @V_NUMERO)
	PRINT 'VALOR DE DATA: ' + CAST(@V_DATA AS VARCHAR)
	PRINT 'VALOR DE DATA: ' + CONVERT(VARCHAR, @V_DATA, 121)
	PRINT 'VALOR DE DATA: ' + CONVERT(VARCHAR, @V_DATA, 120)
	PRINT 'VALOR DE DATA: ' + CONVERT(VARCHAR, @V_DATA, 105)
END
GO

/* BANCO PARA TSQL */

CREATE DATABASE TSQLING
USE TSQLING
GO

CREATE TABLE CARROS (
	CARRO VARCHAR(20),
	FABRICANTE VARCHAR(30)
)
GO

INSERT INTO CARROS VALUES ('KA', 'FORD')
INSERT INTO CARROS VALUES ('FIEST', 'FORD')
INSERT INTO CARROS VALUES ('PRISMA', 'FORD')
INSERT INTO CARROS VALUES ('CLIO', 'RENAULT')
INSERT INTO CARROS VALUES ('KA', 'RENAULT')
INSERT INTO CARROS VALUES ('CHEVETE', 'CHEVROLET')
INSERT INTO CARROS VALUES ('OMEGA', 'CHEVROLET')
INSERT INTO CARROS VALUES ('PALIO', 'FIAT')
INSERT INTO CARROS VALUES ('DOBLO', 'FIAT')
INSERT INTO CARROS VALUES ('UNO', 'FIAT')
INSERT INTO CARROS VALUES ('GOL', 'VOLKSWAGEN')
GO

DECLARE
	@V_CONT_FORD INT,
	@V_CONT_FIAT INT
BEGIN
	-- O SELECT PRECISA RETORNAR UMA SÓ COLUNA
	-- E UM RESULTADO
	SET @V_CONT_FORD = (SELECT COUNT(*) FROM CARROS
	WHERE FABRICANTE = 'FORD')

	PRINT 'QUANTIDADE FORD: ' + CAST(@V_CONT_FORD AS VARCHAR)

	-- METODO 2

	SELECT @V_CONT_FIAT = COUNT(*) FROM CARROS
	WHERE FABRICANTE = 'FIAT'

	PRINT 'QUANTIDADE FIAT: ' + CONVERT(VARCHAR, @V_CONT_FIAT)
		
END
GO

/* BLOCOS IF E ELSE */

DECLARE
	@NUMERO INT = 5
BEGIN

	IF @NUMERO = 5 --BOOLEAN
		PRINT 'O VALOR É VERDADEIRO'
	ELSE 
		PRINT 'O VALOR É FALSO'
END
GO

/* CASE */

DECLARE
	@CONTADOR INT = 5

BEGIN
	SELECT -- CASE REPRESENTA UMA COLUNA
	CASE 
		WHEN FABRICANTE = 'FIAT' THEN 'FAIXA 1'
		WHEN FABRICANTE = 'CHEVROLET' THEN 'FAIXA 2'
		ELSE 'OUTRAS FAIXAS'
	END AS "INFORMAÇÕES",
	* FROM CARROS
END	
GO

/* LOOPS WHILE */

DECLARE
	@V INT = 1
BEGIN

	WHILE (@V < 15)
	BEGIN
		PRINT 'VALOR DE @V: ' + CONVERT(VARCHAR, @V)
		SET @V = @V + 1
	END
END
GO


/* EXERCICIO, TRANSFORMAR IF EM PROCEDURE */

CREATE PROC VERIFICAR @NUMERO INT
AS
BEGIN
	IF @NUMERO = 5 --BOOLEAN
		PRINT 'O VALOR É VERDADEIRO'
	ELSE 
		PRINT 'O VALOR É FALSO'
END
GO

EXEC VERIFICAR 6