-- ESTRUTURA DE UMA TRIGGER

DELIMITER $

CREATE TRIGGER NOME
BEFORE/AFTER INSERT/DELETE/UPDATE ON TABELA
FOR EACH ROW (PARA CADA LINHA)
BEGIN -> INICIO
		COMANDO SQL;
END -> FIM
$

-- ------------------------------------------

CREATE DATABASE  AULA16;
USE AULA16;

CREATE TABLE USUARIO(
		IDUSU INT PRIMARY KEY AUTO_INCREMENT,
		NOME VARCHAR(30),
		LOGIN VARCHAR(30),
		SENHA VARCHAR(100)
);

CREATE TABLE BKPUSUARIO(
		IDBKP INT PRIMARY KEY AUTO_INCREMENT,
		IDUSU INT,
		NOME VARCHAR(30),
		LOGIN VARCHAR(30)
		
);

DELIMITER $

CREATE TRIGGER BKPUSUARIO
BEFORE DELETE ON USUARIO
FOR EACH ROW
BEGIN
		INSERT INTO BKPUSUARIO 
		VALUES(NULL,OLD.IDUSU,OLD.NOME,OLD.LOGIN);
END
$

INSERT INTO USUARIO(NOME,LOGIN,SENHA) VALUES('Marcus','Ryugaki','mugen1');

SELECT * FROM USUARIO;

DELETE FROM USUARIO
WHERE IDUSU = 1;

SELECT * FROM BKPUSUARIO;

-- ---------------------------------------------------------------------------