/* PROCEDURES */

/* SP = STORAGED PROCEDURES */

CREATE TABLE PESSOA(
	IDPES INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(60) NOT NULL,
	SEXO CHAR(1) NOT NULL CHECK (SEXO IN('M','F')), --ENUM
	NASCIMENTO DATE NOT NULL
)
GO

CREATE TABLE TELEFONE(
	IDTEL INT PRIMARY KEY IDENTITY,
	TIPO CHAR(3) CHECK(TIPO IN('RES','CEL','COM')),
	NUMERO CHAR(10) NOT NULL,
	ID_PES INT
)
GO

ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE_PESSOA
FOREIGN KEY(ID_PES) REFERENCES PESSOA(IDPES)
ON DELETE CASCADE
GO

INSERT INTO PESSOA VALUES('ANTONIO', 'M', '1999-08-12')
INSERT INTO PESSOA VALUES('CLEIDE', 'F', '1950-12-23')
INSERT INTO PESSOA VALUES('DANIEL', 'M', '2001-01-31')

INSERT INTO TELEFONE VALUES('CEL' ,'12512598', 1)
INSERT INTO TELEFONE VALUES('COM' ,'45123598', 1)
INSERT INTO TELEFONE VALUES('CEL' ,'19842123', 2)
INSERT INTO TELEFONE VALUES('CEL' ,'12765558', 2)
INSERT INTO TELEFONE VALUES('COM' ,'19765438', 3)
INSERT INTO TELEFONE VALUES('COM' ,'12345679', 2)
INSERT INTO TELEFONE VALUES('CEL' ,'12117744', 3)
GO

/* CRIANDO A PROCEDURE */

CREATE PROC SOMA
AS
	SELECT 10 + 10 AS SOMA
GO

SOMA
GO

/* PROFISSIONAL = EXEC SOMA GO */

/* DINAMICAS = PROCEDURES COM PARAMETROS */

CREATE PROC CALCULAR @NUM1 INT, @NUM2 INT
AS
	SELECT @NUM1 + @NUM2 AS RESULTADO
GO

EXEC CALCULAR 100, 64
GO

/* PARA DELETAR PROCEDURE */

DROP PROC SOMA
GO

/* PROCEDURES EM TABELAS */

SELECT NOME, NUMERO
FROM PESSOA
INNER JOIN TELEFONE
ON IDPES=ID_PES
WHERE TIPO = 'CEL'
GO

/* TRAZER OS TELEFONES DE ACORDO COM O TIPO PASSADO */
CREATE PROC TELEFONES @TIPO CHAR(3)
AS
	SELECT NOME, NUMERO
	FROM PESSOA
	INNER JOIN TELEFONE
	ON IDPES=ID_PES
	WHERE TIPO = @TIPO
GO

EXEC TELEFONES 'COM'
GO

/* PARAMETROS DE OUTPUT */

SELECT TIPO, COUNT(*) AS QUANTIDADE
FROM TELEFONE
GROUP BY TIPO
GO

CREATE PROC GETTIPO @TIPO CHAR(3), @CONTADOR INT OUTPUT
AS
	SELECT @CONTADOR = COUNT(*)
	FROM TELEFONE
	WHERE TIPO = @TIPO
GO

/* EXECUCAO DA PROC COM PARAMETRO DE SAIDA */

DECLARE @SAIDA INT
EXEC GETTIPO 'CEL', @CONTADOR = @SAIDA OUTPUT
SELECT @SAIDA
GO

/* PROCEDURE DE CADASTRO */

SELECT @@IDENTITY -- GUARDA O NUMERO DA ULTIMA PK INSERIDA
GO

CREATE PROC CADASTRO @NOME VARCHAR(30), @SEXO CHAR(1), @NASCIMENTO DATE,
@TIPO CHAR(3), @NUMERO VARCHAR(10)
AS
	DECLARE @FK INT

	INSERT INTO PESSOA VALUES(@NOME, @SEXO, @NASCIMENTO)

	SET @FK = (SELECT IDPES FROM PESSOA WHERE IDPES = @@IDENTITY)

	INSERT INTO TELEFONE VALUES(@TIPO, @NUMERO, @FK)
GO

CADASTRO 'JORGE', 'M', '1989-02-02', 'CEL', '993939190'
GO

SELECT PESSOA.*, TELEFONE.*
FROM PESSOA
INNER JOIN TELEFONE
ON IDPES = ID_PES
GO




