/* ALTERAR TABELA */

CREATE TABLE TABELA(
COLUNA1 VARCHAR(30),
COLUNA2 VARCHAR(30),
COLUNA3 VARCHAR(30)
);

-- ADICIONANDO UMA PK
ALTER TABLE TABELA
ADD PRIMARY KEY (COLUNA1);

-- ADICIONAR UMA COLUNA NA ULTIMA POS
ALTER TABLE TABELA
ADD COLUNA4 VARCHAR(30);

-- ADICIONAR UMA COLUNA NA ULTIMA POS
ALTER TABLE TABELA
ADD COLUNA VARCHAR(30) NOT NULL UNIQUE
AFTER COLUNA2;

-- ALTERANDO TIPO DE COLUNA
ALTER TABLE TABELA
MODIFY COLUNA2 DATE NOT NULL;

-- RENOMEANDO TABELA
ALTER TABLE TABELA
RENAME PESSOA;

CREATE TABLE TIME(
		IDTIM INT PRIMARY KEY AUTO_INCREMENT,
		TIME VARCHAR(30) NOT NULL,
		ID_PES VARCHAR(30)
);

-- ADICIONANDO FOREIGN KEY
ALTER TABLE TIME
ADD FOREIGN KEY (ID_PES) REFERENCES PESSOA(COLUNA1); 

-- VERIFICAR AS CHAVES
SHOW CREATE TABLE TIME;