/* MODELAGEM DE CLIENTE */

CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE CLIENTE(
	IDCLI INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE, /* SERVE PARA TORNAR UNICO O ATRIBUTO DO REGISTRO */
	CPF VARCHAR(15) UNIQUE NOT NULL
);

CREATE TABLE TELEFONE(
	IDTEL INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('COM','RES','CEL'),
	NUMERO VARCHAR(15),
	ID_CLI INT,
	FOREIGN KEY(ID_CLI) REFERENCES CLIENTE(IDCLI)
);

CREATE TABLE ENDERECO(
IDEND INT PRIMARY KEY AUTO_INCREMENT,
RUA VARCHAR(30) NOT NULL,
BAIRRO VARCHAR(30) NOT NULL,
CIDADE VARCHAR(30) NOT NULL,
ESTADO CHAR(2) NOT NULL,
ID_CLI INT UNIQUE,
FOREIGN KEY(ID_CLI) REFERENCES CLIENTE(IDCLI)
);

/* FOREIGN KEY - FK = CHAVE PRIMARIA DE OUTRA TABELA*/
/* EM RELACIONAMENTOS 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA */

/* EM RELACIONAMENTOS 1 X N A CHAVE ESTRANGEIRA FICARA NA TABELA N */

INSERT INTO CLIENTE(NOME,SEXO,EMAIL,CPF) VALUES('Marcus','M','Marcus@sql.com','857.380.000-30');
INSERT INTO CLIENTE(NOME,SEXO,EMAIL,CPF) VALUES('Cecilia','F','Cecilia@sql.com','380.857.000-40');
INSERT INTO CLIENTE(NOME,SEXO,EMAIL,CPF) VALUES('Ramos','M','Ramos@sql.com','123.456.789-60');
INSERT INTO CLIENTE(NOME,SEXO,EMAIL,CPF) VALUES('Dario','M','Dario@sql.com','987.654.321-50');
INSERT INTO CLIENTE(NOME,SEXO,EMAIL,CPF) VALUES('Althea','F','Althea@sql.com','939.993.919-80');

INSERT INTO ENDERECO(ID_CLI,RUA,BAIRRO,CIDADE,ESTADO) VALUES(5,'Rua A','MVI','Gravatai','RS');
INSERT INTO ENDERECO(ID_CLI,RUA,BAIRRO,CIDADE,ESTADO) VALUES(4,'Rua B','MVII','Gravatai','RS');
INSERT INTO ENDERECO(ID_CLI,RUA,BAIRRO,CIDADE,ESTADO) VALUES(3,'Rua C','MVIII','Gravatai','RS');
INSERT INTO ENDERECO(ID_CLI,RUA,BAIRRO,CIDADE,ESTADO) VALUES(2,'Rua D','Amadeu','Campinas','SP');
INSERT INTO ENDERECO(ID_CLI,RUA,BAIRRO,CIDADE,ESTADO) VALUES(1,'Rua E','Carlos Lacerda','Belo Horizonte','MG');

INSERT INTO TELEFONE(TIPO,NUMERO,ID_CLI) VALUES('RES','51 3421-4218',1);
INSERT INTO TELEFONE(TIPO,NUMERO,ID_CLI) VALUES('COM','55 98574-2321',5);
INSERT INTO TELEFONE(TIPO,NUMERO,ID_CLI) VALUES('CEL','71 98598-3213',5);
INSERT INTO TELEFONE(TIPO,NUMERO,ID_CLI) VALUES('COM','88 98888-9190',2);
INSERT INTO TELEFONE(TIPO,NUMERO,ID_CLI) VALUES('RES','81 3125-1214',5);
INSERT INTO TELEFONE(TIPO,NUMERO,ID_CLI) VALUES('CEL','51 99393-9190',1);
INSERT INTO TELEFONE(TIPO,NUMERO,ID_CLI) VALUES('RES','88 3678-1234',2);
INSERT INTO TELEFONE(TIPO,NUMERO,ID_CLI) VALUES('COM','81 3042-3529',1);