/*ORGANIZAR FISICA E LOGICAMENTE UM BANCO DE DADOS

1- CRIAR ARQUIVO PARA MKT
2- CRIAR ARQUIVO PARA RH
3- CRIAR ARQUIVO GERAL
4- DEIXAR O MDF APENAS COM O DICIONÁRIO DE DADOS
5- CRIAR DOIS GRUPOS DE ARQUIVOS (PRIMARY - MDF)
*/

CREATE TABLE TB_EMPRESA(
	ID INT,
	NOME VARCHAR(50)
)
GO