/* USANDO OPERADORES LOGICOS EM BUSCAS */

/* USANDO OU */
SELECT NOME,SEXO,CPF FROM CLIENTE
WHERE ENDERECO = 'Gravatai' OR ENDERECO LIKE '%SP';
/* RETORNARA DUAS ENTRADAS, POIS SAO DOIS ATRIBUTOS DISTINTOS */

/* USANDO E */
SELECT NOME,SEXO,CPF FROM CLIENTE
WHERE ENDERECO = 'Gravatai' AND SEXO = 'F';
/* VAI RETORNAR NADA, POIS NAO EXISTE NINGUEM COM ESSAS DUAS CONDICOES JUNTAS */

/* COUNT= CONTA QUANTOS REGISTROS TEM NO BANCO DE DADOS */
SELECT COUNT(*) FROM CLIENTE;

/* SERIA BOM USAR ALIAS NO COUNT (LEMBRANDO DA PERFORMANCE) */
SELECT COUNT(*) AS "QUANTIDADE" FROM CLIENTE;

/* GROUP BY AGRUPA OS ATRIBUTOS DA TABELA CONTADA */
SELECT SEXO, COUNT(*) AS "QUANTIDADE" FROM CLIENTE GROUP BY SEXO;

/* ORGANIZANDO A TABELA POR DOIS ATRIBUTOS, PEGAR SOMENTE OS REGISTROS FEMININOS */
SELECT SEXO,ENDERECO, COUNT(*) AS "QUANTIDADE" FROM CLIENTE
WHERE SEXO = 'F' 
GROUP BY SEXO,ENDERECO;

/* NA HORA DE CRIAR CRITERIOS, COLOCAR O QUE TEM MENOS REGISTROS(POSSIVEIS) POIS ASSIM DEMORA MENOS PARA ACHAR */
SELECT NOME,CPF,ENDERECO FROM CLIENTE
WHERE NOME= 'Valdomiro Santiago' OR SEXO = 'M'

/* PROCURANDO POR VALORES NULOS */
SELECT SEXO,ENDERECO, COUNT(*) AS "QUANTIDADE" FROM CLIENTE
WHERE SEXO IS NULL;
/* TAMBEM SERVE O IS NOT NULL*/ 