-- CURSORES

CREATE DATABASES CURSORES;
USE CURSORES;

CREATE TABLE VENDEDOR(
		IDVEN INT PRIMARY KEY AUTO_INCREMENT,
		NOME VARCHAR(50),
		JAN INT,
		FEV INT,
		MAR INT
);

INSERT INTO VENDEDOR(NOME,JAN,FEV,MAR) VALUES('Marcus',32000,31000,40000);
INSERT INTO VENDEDOR(NOME,JAN,FEV,MAR) VALUES('Felipe',22000,11000,30000);
INSERT INTO VENDEDOR(NOME,JAN,FEV,MAR) VALUES('Augusto',42000,45000,50000);
INSERT INTO VENDEDOR(NOME,JAN,FEV,MAR) VALUES('Cury',12300,52000,60000);
INSERT INTO VENDEDOR(NOME,JAN,FEV,MAR) VALUES('Alisson',64000,36000,70000);
INSERT INTO VENDEDOR(NOME,JAN,FEV,MAR) VALUES('Ian',16000,38000,80000);

SELECT NOME, (JAN+FEV+MAR) AS "TOTAL DE LUCRO",
TRUNCATE((JAN+FEV+MAR)/3,2) AS "MEDIA POR MES"
FROM VENDEDOR;

-- ---------------------------------------------------------------------------

CREATE TABLE VENDEDOR_TOTAL(
		IDVEN INT PRIMARY KEY AUTO_INCREMENT,
		NOME VARCHAR(50),
		JAN INT,
		FEV INT,
		MAR INT,
		TOTAL INT,
		MEDIA INT
);

DELIMITER $

CREATE PROCEDURE INSERIRDADOS()
BEGIN
		DECLARE FIM INT DEFAULT 0;
		DECLARE MES1,MES2,MES3,VTOTAL,VMEDIA INT;
		DECLARE VNOME VARCHAR(50);
		
		DECLARE REG CURSOR FOR(
		SELECT NOME,JAN,FEV,MAR FROM VENDEDOR 
		);
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;
		OPEN REG;
		-- REPEAT
		REPEAT 
			FETCH REG INTO VNOME,MES1,MES2,MES3;
				IF NOT FIM THEN
				
					SET VTOTAL = (MES1+MES2+MES3);
					SET VMEDIA = VTOTAL/3;
					INSERT INTO VENDEDOR_TOTAL VALUES(NULL,VNOME,MES1,MES2,MES3,VTOTAL,VMEDIA);
					
				END IF;
		UNTIL FIM END REPEAT;
		CLOSE REG;
END
$

CALL INSERIRDADOS();