-- ALTERANDO O BANCO DE BACKUP

ALTER TABLE BKP_COMERCIO.BKP_PRODUTO
ADD EVENTO CHAR(1);

DROP TRIGGER BACKUP_PRODUTO_DEL;
DROP TRIGGER BACKUP_PRODUTO_INS;

-- TRIGGERS COM EVENTO

DELIMITER $ 

CREATE TRIGGER TGR_BACKUP_PRODUTO_DEL
BEFORE DELETE ON PRODUTO
FOR EACH ROW
BEGIN
		INSERT INTO BKP_COMERCIO.BKP_PRODUTO(IDPRO,NOME,VALOR,EVENTO) 
		VALUES(OLD.IDPRO,OLD.NOME,OLD.VALOR,'D');
END
$

CREATE TRIGGER TGR_BACKUP_PRODUTO_INSERT
AFTER INSERT ON PRODUTO
FOR EACH ROW
BEGIN
		INSERT INTO BKP_COMERCIO.BKP_PRODUTO(IDPRO,NOME,VALOR,EVENTO) 
		VALUES(NEW.IDPRO,NEW.NOME,NEW.VALOR,'I');
END
$

-- TRIGGER DE AUDITORIA

DROP DATABASE COMERCIO;
DROP DATABASE BKP_COMERCIO;

CREATE DATABASE COMERCIO;
USE COMERCIO;

CREATE TABLE PRODUTO(
		IDPRO INT PRIMARY KEY AUTO_INCREMENT,
		NOME VARCHAR(30),
		VALOR FLOAT(10,2)
		
);

INSERT INTO PRODUTO (NOME,VALOR) VALUES('Livro Curso Modelagem',50.99);
INSERT INTO PRODUTO (NOME,VALOR) VALUES('Livro A Maldicao do Cigano',34.50);
INSERT INTO PRODUTO (NOME,VALOR) VALUES('Livro O Iluminado',79.00);
INSERT INTO PRODUTO (NOME,VALOR) VALUES('Livro Carrie a Estranha',24.00);

CREATE DATABASE BKP_COMERCIO;
USE BKP_COMERCIO;

CREATE TABLE BKP_PRODUTO(
		IDBKP INT PRIMARY KEY AUTO_INCREMENT,
		IDPRO INT,
		NOME VARCHAR(30),
		VALOR_ORIGINAL FLOAT(10,2),
		VALOR_ALTERADO FLOAT(10,2),
		DATA DATETIME,
		USUARIO VARCHAR(30),
		EVENTO VARCHAR(10)
);
-- ALGUNS COMANDOS IMPORTANTES

SELECT NOW();
SELECT CURRENT_USER;

DELIMITER $

CREATE TRIGGER AUDIT_BKP_PRODUTO
AFTER UPDATE ON PRODUTO
FOR EACH ROW
BEGIN
		INSERT INTO BKP_COMERCIO.BKP_PRODUTO VALUES(NULL,OLD.IDPRO,OLD.NOME,OLD.VALOR,NEW.VALOR,NOW(),CURRENT_USER(),"UPDATE");
END
$

UPDATE PRODUTO
SET VALOR = 33.50
WHERE IDPRO = 1;
