-- COMUNICACAO ENTRE BANCOS

CREATE DATABASE COMERCIO;
USE COMERCIO;

CREATE TABLE PRODUTO(
		IDPRO INT PRIMARY KEY AUTO_INCREMENT,
		NOME VARCHAR(30),
		VALOR FLOAT(10,2)
		
);

STATUS

CREATE DATABASE BKP_COMERCIO;
USE BKP_COMERCIO;

CREATE TABLE BKP_PRODUTO(
		IDBKP INT PRIMARY KEY AUTO_INCREMENT,
		IDPRO INT,
		NOME VARCHAR(30),
		VALOR FLOAT(10,2)
);

USE COMERCIO;

INSERT INTO BKP_COMERCIO.BKP_PRODUTO (IDPRO,NOME,VALOR) VALUES (1000,'TESTE',0.0);

SELECT * FROM BKP_COMERCIO.BKP_PRODUTO;

-- CRIANDO TRIGGER (errado)
DELIMITER $

CREATE TRIGGER BACKUP_PRODUTO
BEFORE INSERT ON PRODUTO
FOR EACH ROW
BEGIN
		INSERT INTO BKP_COMERCIO.BKP_PRODUTO (IDPRO,NOME,VALOR) 
		VALUES (NEW.IDPRO,NEW.NOME,NEW.VALOR);
END
$

-- VERIFICANDO A TRIGGER

INSERT INTO PRODUTO (NOME,VALOR) VALUES('Livro Curso Modelagem',50.99);
INSERT INTO PRODUTO (NOME,VALOR) VALUES('Livro A Maldicao do Cigano',34.50);
INSERT INTO PRODUTO (NOME,VALOR) VALUES('Livro O Iluminado',79.00);
INSERT INTO PRODUTO (NOME,VALOR) VALUES('Livro Carrie a Estranha',24.00);

SELECT * FROM PRODUTO;

SELECT * FROM BKP_COMERCIO.BKP_PRODUTO;

-- TRIGGER PARA CASO DELETE

DELIMITER $

CREATE TRIGGER BACKUP_PRODUTO_DEL
BEFORE DELETE ON PRODUTO
FOR EACH ROW
BEGIN
		INSERT INTO BKP_COMERCIO.BKP_PRODUTO (IDPRO,NOME,VALOR) 
		VALUES (OLD.IDPRO,OLD.NOME,OLD.VALOR);
END
$

DELETE FROM PRODUTO WHERE IDPRO = 1;

DROP TRIGGER BKP_PRODUTO;

DELIMITER $

CREATE TRIGGER BACKUP_PRODUTO_INS
AFTER INSERT ON PRODUTO
FOR EACH ROW
BEGIN
		INSERT INTO BKP_COMERCIO.BKP_PRODUTO (IDPRO,NOME,VALOR) 
		VALUES (NEW.IDPRO,NEW.NOME,NEW.VALOR);
END
$