-- FUNCOES DE AGREGACAO NUMERICA

CREATE TABLE VENDEDOR(
IDVEN INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL,
SEXO ENUM('M','F') NOT NULL,
JANEIRO FLOAT(10,2),
FEVEREIRO FLOAT(10,2),
MARCO FLOAT(10,2)
);

INSERT INTO VENDEDOR(NOME,SEXO,JANEIRO,FEVEREIRO,MARCO) VALUES('Tiago Costa','M',78550.12,12345.99,10000.19);
INSERT INTO VENDEDOR(NOME,SEXO,JANEIRO,FEVEREIRO,MARCO) VALUES('Pedro Rutz','M',71230.22,7948.89,90000.49);
INSERT INTO VENDEDOR(NOME,SEXO,JANEIRO,FEVEREIRO,MARCO) VALUES('Maria Betoneira','F',51230.32,5436.79,75383.59);
INSERT INTO VENDEDOR(NOME,SEXO,JANEIRO,FEVEREIRO,MARCO) VALUES('Joao Almeida','M',178660.52,9583.69,12953.15);
INSERT INTO VENDEDOR(NOME,SEXO,JANEIRO,FEVEREIRO,MARCO) VALUES('Lidia Lutz','F',987650.22,12345.59,66564.97);
INSERT INTO VENDEDOR(NOME,SEXO,JANEIRO,FEVEREIRO,MARCO) VALUES('Beatriz Rosa','F',172354.33,12345.79,957764.12);
INSERT INTO VENDEDOR(NOME,SEXO,JANEIRO,FEVEREIRO,MARCO) VALUES('Charles Dickens','M',78550.76,12345.12,5678912.13);
INSERT INTO VENDEDOR(NOME,SEXO,JANEIRO,FEVEREIRO,MARCO) VALUES('Ruth Rocha','F',1234.56,19345.87,675563.15);

-- FUNCAO MAX - TRAZ O VALOR MAXIMO DE UMA COLUNA

SELECT MAX(FEVEREIRO) AS "MAIOR LUCRO EM FEVEREIRO"
FROM VENDEDOR;

-- FUNCAO MIN - TRAZ O VALOR MINIMO DE UMA COLUNA

SELECT MIN(FEVEREIRO) AS "MENOR LUCRO EM FEVEREIRO"
FROM VENDEDOR;

-- FUNCAO AVG - TRAZ A MEDIA DE UMA COLUNA

SELECT AVG(FEVEREIRO) AS "MEDIA DE LUCRO EM FEVEREIRO"
FROM VENDEDOR;

-- VARIAS FUNCOES

SELECT MAX(JANEIRO) AS MAIOR_JAN,
	   MIN(JANEIRO) AS MENOR_JAN,
	   AVG(JANEIRO) AS MEDIA_JAN
FROM VENDEDOR;

--TRUNCATE

SELECT MAX(JANEIRO) AS MAIOR_JAN,
	   MIN(JANEIRO) AS MENOR_JAN,
	   TRUNCATE(AVG(JANEIRO),2) AS MEDIA_JAN
FROM VENDEDOR;

-- FUNCAO SUM()

SELECT SUM(JANEIRO) AS TOTAL_JAN,
SUM(FEVEREIRO) AS TOTAL_FEV,
SUM(MARCO) AS TOTAL_MAR
FROM VENDEDOR;

-- VENDA POR SEXO
SELECT SEXO, SUM(MARCO) AS TOTAL_MAR
FROM VENDEDOR
GROUP BY SEXO;