-- AUTO RELACIONAMENTO

CREATE TABLE CURSO(
IDCUR INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30),
CH INT,
VALOR FLOAT(10,2),
ID_PRE INT
);

ALTER TABLE CURSO 
ADD CONSTRAINT FK_IDPRE
FOREIGN KEY (ID_PRE) REFERENCES CURSO(IDCUR);

INSERT INTO CURSO(NOME,CH,VALOR) VALUES("Banco de Dados Relacional",20,400.00);
INSERT INTO CURSO(NOME,CH,VALOR,ID_PRE) VALUES("Business Inteligence",40,800.00,1);
INSERT INTO CURSO(NOME,CH,VALOR,ID_PRE) VALUES("Relatorios Avancados",20,600.00,2);
INSERT INTO CURSO(NOME,CH,VALOR) VALUES("Logica de Programacao",60,200.00);
INSERT INTO CURSO(NOME,CH,VALOR,ID_PRE) VALUES("Ruby",20,350.00,4);

SELECT NOME,
	   VALOR,
	   CH AS "CARGA HORARIA",
	   IFNULL(ID_PRE,"SEM PRE REQ.") AS "PRE REQUISITO" 
FROM CURSO;

/* EXERCICIO : NOME,VALOR,CH, NOME PRE REQ */

SELECT C.NOME,C.VALOR,C.CH,IFNULL(CR.NOME,"------") AS "NOME DO PRE REQ"
FROM CURSO C
LEFT JOIN CURSO CR -- PARA MOSTRAR TODOS, MESMO OS SEM PRE REQ
ON C.ID_PRE = CR.IDCUR;