/* CHARINDEX */

USE EMPRESA
GO

SELECT NOME, CHARINDEX('A', NOME ) AS 'INDICE' FROM ALUNO
GO

/* BULK INSERT - IMPORTAR ARQUIVOS */

CREATE TABLE LANCAMENTO_CONTABIL (
	CONTA INT,
	VALOR INT,
	TIPO CHAR(1)
);
GO

BULK INSERT LANCAMENTO_CONTABIL 
FROM 'C:\Users\Marcus Ruas\Downloads\CONTAS.TXT'
WITH (
 FIRSTROW = 2,
 DATAFILETYPE = 'char',
 FIELDTERMINATOR = '\t',
 ROWTERMINATOR = '\n'
 -- \t = TAB, \n = NOVA LINHA
)
GO

SELECT * FROM LANCAMENTO_CONTABIL
GO