/* EXERCICIO OFICINA DO SR JOSE */

/*
SR JOSE QUER MODERNIZAR A SUA OFICINA, E POR ENQUANTO, CADASTRAR OS CARROS QUE ENTRAM
PARA REALIZAR SERVICOS E OS SEUS RESPECTIVOS DONOS. SR JOSE MENCIONOU QUE CADA CLIENTE
POSSUI APENAS UM CARRO.UM CARRO POSSUI UMA MARCA. SR JOSE TAMBEM QUER SABER AS
CORES DOS CARROS PARA TER IDEIA DE QUAL TINTA COMPRAR, E INFORMA QUE UM CARRO PODE TER
MAIS DE UMA COR. SR JOSE NECESSITA ARMAZENAR OS TELEFONES DOS CLIENTES, MAS NAO QUER
QUE ELES SEJAM OBRIGATORIOS
*/

CREATE DATABASE EXEC1;
USE EXEC1;

/* -------------------------------------------------------------------------------------------------- */

CREATE TABLE CLIENTE (
IDCLI INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
SEXO ENUM('M','F') NOT NULL,
CPF VARCHAR(15) NOT NULL UNIQUE,
EMAIL VARCHAR(60) NOT NULL
);

CREATE TABLE CARRO(
IDCAR INT PRIMARY KEY AUTO_INCREMENT,
PLACA VARCHAR(10) NOT NULL UNIQUE,
MARCA VARCHAR(15) NOT NULL,
ID_CLI INT UNIQUE,
FOREIGN KEY (ID_CLI) REFERENCES CLIENTE (IDCLI)
);

CREATE TABLE COR(
IDCOR INT PRIMARY KEY AUTO_INCREMENT,
COR VARCHAR(25) NOT NULL,
ID_CAR INT,
FOREIGN KEY (ID_CAR) REFERENCES CARRO(IDCAR)
);

CREATE TABLE ENDERECO(
IDEND INT PRIMARY KEY AUTO_INCREMENT,
ESTADO CHAR(2) NOT NULL,
BAIRRO VARCHAR(30) NOT NULL,
CIDADE VARCHAR(30) NOT NULL,
ID_CLI INT UNIQUE,
FOREIGN KEY (ID_CLI) REFERENCES CLIENTE(IDCLI)
);

CREATE TABLE TELEFONE(
IDTEL INT PRIMARY KEY AUTO_INCREMENT,
TIPO ENUM('RES','COM','CEL') NOT NULL,
NUMERO VARCHAR(15) NOT NULL,
ID_CLI INT,
FOREIGN KEY (ID_CLI) REFERENCES CLIENTE(IDCLI)
);

/* -------------------------------------------------------------------------------------------------- */

INSERT INTO CLIENTE(NOME,SEXO,CPF,EMAIL) VALUES('Marcus Ruas','M','888888888','Marcus@sql.com');
INSERT INTO CLIENTE(NOME,SEXO,CPF,EMAIL) VALUES('Fernanda Lima','F','123456789','Fernanda@sql.com');

INSERT INTO CARRO(PLACA,MARCA,ID_CLI) VALUES('EMW-3682','Volkswagen',2);
INSERT INTO CARRO(PLACA,MARCA,ID_CLI) VALUES('EQI-4199','Klio',1);

INSERT INTO COR(COR,ID_CAR) VALUES('Vemelho',1);
INSERT INTO COR(COR,ID_CAR) VALUES('Azul',1);
INSERT INTO COR(COR,ID_CAR) VALUES('Verde',2);
INSERT INTO COR(COR,ID_CAR) VALUES('Amarelo',2);

INSERT INTO ENDERECO(ESTADO,BAIRRO,CIDADE,ID_CLI) VALUES('RS','Morada do Vale I','Gravatai',1);
INSERT INTO ENDERECO(ESTADO,BAIRRO,CIDADE,ID_CLI) VALUES('SP','Bairro Jardim','Ijui',2);

INSERT INTO TELEFONE(TIPO,NUMERO,ID_CLI) VALUES('CEL','999998888',2);
INSERT INTO TELEFONE(TIPO,NUMERO,ID_CLI) VALUES('CEL','987654321',1);
INSERT INTO TELEFONE(TIPO,NUMERO,ID_CLI) VALUES('RES','34214218',1);
INSERT INTO TELEFONE(TIPO,NUMERO,ID_CLI) VALUES('RES','30421686',2);

/* -------------------------------------------------------------------------------------------------- */

SELECT CL.NOME,CL.CPF,C.MARCA,CR.COR,E.CIDADE,E.ESTADO,T.TIPO,T.NUMERO
FROM CLIENTE CL
INNER JOIN CARRO C
ON CL.IDCLI = C.ID_CLI
INNER JOIN COR CR
ON CL.IDCLI = CR.ID_CAR
INNER JOIN ENDERECO E
ON CL.IDCLI = E.ID_CLI
INNER JOIN TELEFONE T
ON CL.IDCLI = T.ID_CLI
WHERE T.TIPO = 'CEL';

/* -------------------------------------------------------------------------------------------------- */