/* EXERCICIO OFICINA DO SR JOSE */

/*
SR JOSE QUER MODERNIZAR A SUA OFICINA, E POR ENQUANTO, CADASTRAR OS CARROS QUE ENTRAM
PARA REALIZAR SERVICOS E OS SEUS RESPECTIVOS DONOS. SR JOSE MENCIONOU QUE CADA CLIENTE
POSSUI APENAS UM CARRO.UM CARRO POSSUI UMA MARCA. SR JOSE TAMBEM QUER SABER AS
CORES DOS CARROS PARA TER IDEIA DE QUAL TINTA COMPRAR, E INFORMA QUE UM CARRO PODE TER
MAIS DE UMA COR. SR JOSE NECESSITA ARMAZENAR OS TELEFONES DOS CLIENTES, MAS NAO QUER
QUE ELES SEJAM OBRIGATORIOS
*/

CREATE DATABASE ExercicioCerto;
USE ExercicioCerto;

/* -------------------------------------------------------------------------------------------------- */

CREATE TABLE CLIENTE (
IDCLI INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
SEXO ENUM('M','F') NOT NULL,
ID_CAR INT UNIQUE
);

CREATE TABLE TELEFONE(
IDTEL INT PRIMARY KEY AUTO_INCREMENT,
TIPO ENUM('RES','COM','CEL') NOT NULL,
NUMERO VARCHAR(15) NOT NULL,
ID_CLI INT
);

CREATE TABLE MARCA(
IDMAR INT PRIMARY KEY AUTO_INCREMENT,
MARCA VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO(
IDCAR INT PRIMARY KEY AUTO_INCREMENT,
PLACA VARCHAR(10) NOT NULL UNIQUE,
MODELO VARCHAR(30) NOT NULL,
ID_MAR INT
);

CREATE TABLE COR(
IDCOR INT PRIMARY KEY AUTO_INCREMENT,
COR VARCHAR(25) UNIQUE NOT NULL
);

CREATE TABLE CARRO_COR(
ID_CAR INT,
ID_COR INT,
PRIMARY KEY (ID_CAR,ID_COR)
);

-- CONSTRAINTS

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY (ID_CLI) 
REFERENCES CLIENTE (IDCLI);

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY (ID_CAR)
REFERENCES CARRO(IDCAR);

ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY (ID_MAR)
REFERENCES MARCA (IDMAR);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARROCOR_COR
FOREIGN KEY (ID_COR)
REFERENCES COR(IDCOR);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARROCOR_CARRO
FOREIGN KEY (ID_CAR)
REFERENCES CARRO(IDCAR);

-- INSERT

-- CARRO
INSERT INTO CARRO(PLACA,MODELO) VALUES('VGT-2222','Uno');
INSERT INTO CARRO(PLACA,MODELO) VALUES('GKU-9001','Gol');
INSERT INTO CARRO(PLACA,MODELO) VALUES('AVG-1234','Palio');
INSERT INTO CARRO(PLACA,MODELO) VALUES('POR-4321','Fox');
INSERT INTO CARRO(PLACA,MODELO) VALUES('ALM-5678','Siena');
INSERT INTO CARRO(PLACA,MODELO) VALUES('FTG-9876','Celta');
INSERT INTO CARRO(PLACA,MODELO) VALUES('MKO-7342','Voyage');
INSERT INTO CARRO(PLACA,MODELO) VALUES('ASD-0129','HB20');
INSERT INTO CARRO(PLACA,MODELO) VALUES('JKL-5612','Corsa');
INSERT INTO CARRO(PLACA,MODELO) VALUES('FGH-1256','Onix');

-- MARCA
INSERT INTO MARCA(MARCA) VALUES('Fiat');
INSERT INTO MARCA(MARCA) VALUES('Volkswagen');
INSERT INTO MARCA(MARCA) VALUES('General Motors');
INSERT INTO MARCA(MARCA) VALUES('Hyundai');

-- COR
INSERT INTO COR(COR) VALUES('Vemelho');
INSERT INTO COR(COR) VALUES('Azul');
INSERT INTO COR(COR) VALUES('Verde');
INSERT INTO COR(COR) VALUES('Amarelo');
INSERT INTO COR(COR) VALUES('Roxo');
INSERT INTO COR(COR) VALUES('Preto');
INSERT INTO COR(COR) VALUES('Branco');
INSERT INTO COR(COR) VALUES('Rosa');
INSERT INTO COR(COR) VALUES('Ciano');
INSERT INTO COR(COR) VALUES('Cinza');
INSERT INTO COR(COR) VALUES('Laranja');

-- MARCAS EM CARROS
UPDATE CARRO SET ID_MAR=1 WHERE IDCAR=1;
UPDATE CARRO SET ID_MAR=2 WHERE IDCAR=2;
UPDATE CARRO SET ID_MAR=1 WHERE IDCAR=3;
UPDATE CARRO SET ID_MAR=2 WHERE IDCAR=4;
UPDATE CARRO SET ID_MAR=1 WHERE IDCAR=5;
UPDATE CARRO SET ID_MAR=3 WHERE IDCAR=6;
UPDATE CARRO SET ID_MAR=2 WHERE IDCAR=7;
UPDATE CARRO SET ID_MAR=4 WHERE IDCAR=8;
UPDATE CARRO SET ID_MAR=3 WHERE IDCAR=9;
UPDATE CARRO SET ID_MAR=3 WHERE IDCAR=10;

-- CARRO_COR
INSERT INTO CARRO_COR VALUES(1,1);
INSERT INTO CARRO_COR VALUES(1,2);
INSERT INTO CARRO_COR VALUES(2,6);
INSERT INTO CARRO_COR VALUES(3,5);
INSERT INTO CARRO_COR VALUES(4,1);
INSERT INTO CARRO_COR VALUES(4,7);
INSERT INTO CARRO_COR VALUES(5,1);
INSERT INTO CARRO_COR VALUES(6,11);
INSERT INTO CARRO_COR VALUES(6,7);
INSERT INTO CARRO_COR VALUES(7,1);
INSERT INTO CARRO_COR VALUES(8,2);
INSERT INTO CARRO_COR VALUES(9,3);
INSERT INTO CARRO_COR VALUES(10,9);
INSERT INTO CARRO_COR VALUES(10,8);
INSERT INTO CARRO_COR VALUES(10,7);

-- CLIENTES
INSERT INTO CLIENTE(NOME,SEXO,ID_CAR) VALUES('Joaquim','M',4);
INSERT INTO CLIENTE(NOME,SEXO,ID_CAR) VALUES('Sonya','F',8);
INSERT INTO CLIENTE(NOME,SEXO,ID_CAR) VALUES('Willian','M',2);
INSERT INTO CLIENTE(NOME,SEXO,ID_CAR) VALUES('Gabriela','F',1);
INSERT INTO CLIENTE(NOME,SEXO,ID_CAR) VALUES('Gian','M',6);
INSERT INTO CLIENTE(NOME,SEXO,ID_CAR) VALUES('Ismar','M',7);
INSERT INTO CLIENTE(NOME,SEXO,ID_CAR) VALUES('Thay','F',5);
INSERT INTO CLIENTE(NOME,SEXO,ID_CAR) VALUES('Sofia','F',3);

-- QUERY

SELECT C.NOME,C.SEXO,CR.PLACA,CR.MODELO,M.MARCA,CL.COR
FROM CLIENTE C
INNER JOIN CARRO CR
ON C.ID_CAR = CR.IDCAR
INNER JOIN MARCA M
ON M.IDMAR = CR.ID_MAR;